### ISSUE TITLE
Link removales

### ISSUE THREAD

**Issue by ghost** [AmrEldib/AlternativesToOnlineServices#12]
Please remove arkOS link under section Personal Cloud Platforms as the project has been disconnected.
https://arkos.io/

Please remove MagPie link under Note Taking as the project has been disconnected.
https://github.com/charlesthomas/magpie

Please remove Bookie link under Bookmark Management as the project seem to be dead and there  http://bmark.us  seems down according to isup.me

**Comment by ghost** [comment]
Please remove Filo link under section Read-It-Later as the project has been disconnected.
http://filo.bzaar.net/

Please remove wekan under section GTD/ToDo software as the outer link links to non-secure site.
https://github.com/wekan/wekan

Questionable item under section Photos named "Trovebox (formally OpenPhoto)"

Please remove Gravit link under section Design tool as the outer link seems to be dead.
http://hub.gravit.io/browser/

Questionable item under section Personal Dashboard named "Reportr"
http://www.reportr.io/

Please adjust the html link referral of the item PDFCreator under section PDF Printer
http://www.arsgeek.com/2007/05/17/5-steps-to-create-a-pdf-printer-print-to-pdf-in-ubuntu/ (404)

Questionable item under section Social Network named "ThinkUp"
https://www.thinkup.com/

Please remove Gravit link under section Social Network tool as the outer link seems to be dead.
http://diasporaproject.org/

Please remove Codebox under section IDE software as the outer link links to non-secure site.
https://www.codebox.io/

Please adjust the html link referral of the item StartSSL under section SSL
http://www.startssl.com/

Please adjust the html link referral of the item IdeaStack under section Linux VPS Hosting
http://ideastack.com/vps.html (404)

**Comment by AmrEldib** [comment]
@vieq Thank you for reviewing the list and offering these suggestions. I've added almost all of them except for these.  
I filed a [report](https://github.com/wekan/wekan/issues/1027) for the link to Wekan.  
Trovebox company [shut down in March 2015](https://en.wikipedia.org/wiki/Trovebox). Community edition is still available.

**Comment by ghost** [comment]
cool 👍
